version: '2'
services:
  app:
    container_name: app.tic-tac-toe
    user: www-data
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-fpm.dockerfile
    volumes:
    - .:/app
    - ./.docker/configs/php-fpm/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    restart: always

  cli:
    container_name: cli.tic-tac-toe
    user: application
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-cli.dockerfile
    volumes:
    - .:/app

  composer:
    container_name: composer.tic-tac-toe
    user: application
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-composer.dockerfile
    volumes:
    - .:/app
    - $HOME/.composer:/home/application/.composer

  node:
    container_name: nodejs.tec-tac-toe
    image: "node:latest"
    user: node
    working_dir: /app
    volumes:
    - .:/app

  nginx:
    container_name: nginx.tic-tac-toe
    image: "nginx:alpine"
    ports:
    - "80:80"
    volumes:
    - ./.docker/configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - .:/app
    restart: always
    links:
    - app
